;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Setup aliases
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defun bc-setup-aliases ()
  (defalias 'ow 'other-window)
  (defalias 'er 'er/expand-region)
  (defalias 'eb 'eval-buffer)
  (defalias 'aj 'ace-jump-mode)
  (defalias 'fp 'find-file-in-project)
  (defalias 'sfj 'semantic-ia-fast-jump)
  (defalias 'scs 'semantic-complete-symbol)
  (defalias 'c 'compile)
  (defalias 'fnd 'find-name-dired)
  (defalias 'ckrs 'clipboard-kill-ring-save)
  (defalias 'r 'rgrep)
  (defalias 'im 'idomenu)
  (defalias 'ft 'bc-ido-find-tag)
  (defalias 'ff 'bc-ido-find-file-in-tag-files)
  (defalias 'lt 'bc-list-tags-current-buffer)
  (defalias 'fo 'ff-find-other-file)
  (defalias 'cy 'clipboard-yank)
  (defalias 'sn 'senator-next-tag)
  (defalias 'sp 'senator-previous-tag)
  (defalias 'qr 'query-replace)
  (defalias 'vtt 'visit-tags-table)
  (defalias 'ir 'indent-region)
  (defalias 'il 'indent-according-to-mode))
